<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Acme.Domain\Acme.Domain.csproj" />
    <ProjectReference Include="..\Acme.Infrastructure\Acme.Infrastructure.csproj" />
  </ItemGroup>
</Project>
